name: Build, Push Docker Image, and Deploy to Server

on:
  push:
    branches:
      - main  # 仅在推送到 main 分支时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 8: 登录到 Docker Hub
      - name: Login to Aliyun Container Registry
        run: echo "${{ secrets.ALI_REGISTRY_PASSWORD }}" | docker login ${{ secrets.ALI_REGISTRY_URL }} -u ${{ secrets.ALI_REGISTRY_USERNAME }} --password-stdin


      # Step 9: 构建并推送 Docker 镜像到 Docker Hub
      - name: Build and push Docker image
        run: |
         docker build -t ${{ secrets.ALI_REGISTRY_URL }}/image-editer-web:latest .
         docker push ${{ secrets.ALI_REGISTRY_URL }}/image-editer-web:latest

     # Step 2: 通过 SSH 部署到远程服务器
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker pull ${{ secrets.ALI_REGISTRY_URL }}/image-editer-web:latest
            sudo docker stop image-editer || true
            sleep 3
            sudo sudo docker rm image-editer || true
            sleep 3
            sudo docker run -d --name image-editer-web -p 9001:80 ${{ secrets.ALI_REGISTRY_URL }}/image-editer-web:latest
